<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\User;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\FileValidator;

class GalleryController extends Controller
{
    /**
     * @Route("/addPicture", name="addPicture")
     */

    public function addGallery(Request $request, ObjectManager $manager)
    {
        $user = $this->getUser();//on récupère l'objet user

//        $Images = $user->getImages;
//        $image = new Image();//on récupère l'objet image
//        $galleryImg = new File($this->getParameter('galleryPicture_directory') . '/' . $image->getLink());
//
//        $image->setLink($galleryImg);
        $image = new Image();
        /*

        if (!empty($user->getProfilPicture()) ){
        $image = new Image();//on crée la la gallerie
        $picture = new File($this->getParameter('galleryPicture_directory') . '/' . $image->getLink());
        $image->setLink($picture);
        }*/


        $form = $this->createFormBuilder($image)//création et configuration du form
                    ->add('name', TextType::class,[
                        'required' => true,
                        'constraints' => [ //on donne les coditions de validation de ce champ
                            new Length([
                                'min' => 3,
                                'max' => 15,
                                'minMessage' => "Minimum 3 caractères",
                                'maxMessage' => "Maximum 15 caractères"
                            ]),
                            new NotBlank( [
                                'message' => "Champs non-rempli"
                            ])

                        ],
                    ])
                    ->add('link', FileType::class,[//on précise qu'il va s'agire d'un fichier
                //ainsi l'utilisateur purra choisir une image et la palcer dans ce champs
                        'required' => true,
                        'constraints' => [
                            new NotBlank( [
                                'message' => "Vous devez choisir un fichier"
                            ])
                        ],
                     ])

                    ->getForm(); //on récupère le formulaire


        $form->handleRequest($request);  // ANALYSE de la requete et ducou symfony lié title content avec $user

        //Verification de la soumission du formulaire
        if($form->isSubmitted() && $form->isValid()) {

            if(!$image->getId()){
                $image->setDate(new \Datetime());
            }
            //upload de fichier

            /** @var UploadedFile $file */
            $file = $image->getLink();

            if( $file instanceof UploadedFile){// si UploadFile est un fichier
                $fileName = $this->generateUniqueFileName().'.'. $file->guessExtension();

                //déplace le fichier image dans le dossier voulu
                $file->move(
                    $this->getParameter('galleryPicture_directory'),
                    $fileName
                );
                $image->setLink($fileName);

            }

            $image->setUser($user);//le many to one de gallery vers user
            $user->addImage($image);

            $Manager = $this->getDoctrine()->getManager();
            $Manager->persist($image);


            $manager->flush();           //on demande au manager de lancer la requete

            return $this->redirectToRoute('ArtistGallery');
        }


        return $this->render('security/galleryAdd.html.twig',[
            'updateProfile' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
